#!usr/bin/env bash

# Domain configuration

# Configure my domain zone:
# www --> 914-lb-01 34.237.76.64
# web-01 --> 914-web-01 34.138.32.248
# web-02 --> 914-web-02 3.226.74.205



subdomains=( "www" "lb-01" "web-01" "web-02" )

run_dig () {
    subdomain=$1
    domain=$2

    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$subdomain" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
}

if [ $# -eq 1 ]; then
    domain="$1"
    for i in "${subdomains[@]}"
    do
	run_dig "$i" "$domain"
    done
elif [ $# -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    run_dig "$subdomain" "$domain"
fi